name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image & Push to Docker Hub  
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile \
          --tag ${{ vars.DOCKERHUB_USERNAME }}/simple-sems-dashboard:latest \
          --tag ${{ vars.DOCKERHUB_USERNAME }}/simple-sems-dashboard:$TAG
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-sems-dashboard:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-sems-dashboard:$TAG
